import type { Metadata } from 'next'
import { Sarabun, Lobster } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const sarabun = Sarabun<'--font-sans'>({
  subsets: ['vietnamese'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-sans',
})

const lobster = Lobster<'--font-curs'>({
  subsets: ['vietnamese'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-curs',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="vi">
      <body className={`${sarabun.variable} ${lobster.variable}`}>
        {children}
      </body>
    </html>
  )
}
