import type { Metadata } from 'next'
import { Lobster, Nunito } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const nunito = Nunito<'--font-sans'>({
  subsets: ['vietnamese'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-sans',
})

const lobster = Lobster<'--font-curs'>({
  subsets: ['vietnamese'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-curs',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='vi'>
      <body className={`${nunito.variable} ${lobster.variable} font-sans`}>{children}</body>
    </html>
  )
}
